/**
 * PDNS-API
 * This is PDNS RESTful API Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelRecord model module.
 * @module model/ModelRecord
 * @version 1.0
 */
class ModelRecord {
    /**
     * Constructs a new <code>ModelRecord</code>.
     * @alias module:model/ModelRecord
     */
    constructor() { 
        
        ModelRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelRecord} obj Optional instance to populate.
     * @return {module:model/ModelRecord} The populated <code>ModelRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelRecord();

            if (data.hasOwnProperty('auth')) {
                obj['auth'] = ApiClient.convertToType(data['auth'], 'Boolean');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('db')) {
                obj['db'] = ApiClient.convertToType(data['db'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('domain_id')) {
                obj['domain_id'] = ApiClient.convertToType(data['domain_id'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ordername')) {
                obj['ordername'] = ApiClient.convertToType(data['ordername'], 'String');
            }
            if (data.hasOwnProperty('prio')) {
                obj['prio'] = ApiClient.convertToType(data['prio'], 'Number');
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ApiClient.convertToType(data['ttl'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} auth
 */
ModelRecord.prototype['auth'] = undefined;

/**
 * @member {String} content
 */
ModelRecord.prototype['content'] = undefined;

/**
 * @member {String} db
 */
ModelRecord.prototype['db'] = undefined;

/**
 * @member {Boolean} disabled
 */
ModelRecord.prototype['disabled'] = undefined;

/**
 * @member {Number} domain_id
 */
ModelRecord.prototype['domain_id'] = undefined;

/**
 * @member {Number} id
 */
ModelRecord.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ModelRecord.prototype['name'] = undefined;

/**
 * @member {String} ordername
 */
ModelRecord.prototype['ordername'] = undefined;

/**
 * @member {Number} prio
 */
ModelRecord.prototype['prio'] = undefined;

/**
 * @member {Number} ttl
 */
ModelRecord.prototype['ttl'] = undefined;

/**
 * @member {String} type
 */
ModelRecord.prototype['type'] = undefined;






export default ModelRecord;

