/**
 * PDNS-API
 * This is PDNS RESTful API Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PdnsApi);
  }
}(this, function(expect, PdnsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PdnsApi.ModelDomain();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelDomain', function() {
    it('should create an instance of ModelDomain', function() {
      // uncomment below and update the code to test ModelDomain
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be.a(PdnsApi.ModelDomain);
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property db (base name: "db")', function() {
      // uncomment below and update the code to test the property db
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property lastCheck (base name: "last_check")', function() {
      // uncomment below and update the code to test the property lastCheck
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property master (base name: "master")', function() {
      // uncomment below and update the code to test the property master
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property notifiedSerial (base name: "notified_serial")', function() {
      // uncomment below and update the code to test the property notifiedSerial
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property records (base name: "records")', function() {
      // uncomment below and update the code to test the property records
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new PdnsApi.ModelDomain();
      //expect(instance).to.be();
    });

  });

}));
